// Level definitions for FLAIR puzzle game - 200 verified solvable levels
import { Level } from './types';
import {
  TETROMINO_I,
  TETROMINO_O,
  TETROMINO_T,
  TETROMINO_S,
  TETROMINO_Z,
  TETROMINO_L,
  TETROMINO_J,
  TRIOMINO_I,
  TRIOMINO_L,
  DOMINO,
  MONOMINO,
  PENTOMINO_P,
  PENTOMINO_F,
} from './shapes';

// Helper to generate a rectangular grid of active cells
const rect = (rows: number, cols: number): [number, number][] => {
  const cells: [number, number][] = [];
  for (let r = 0; r < rows; r++) {
    for (let c = 0; c < cols; c++) {
      cells.push([r, c]);
    }
  }
  return cells;
};

// =====================================================
// VERIFIED BLOCKED CELLS - Generated by backtracking solver
// Each configuration has been verified to be solvable
// =====================================================
const VERIFIED_BLOCKED: Record<number, [number, number][]> = {
  10: [[0, 2], [1, 2]],
  11: [[1, 1]],
  12: [[1, 3], [0, 3], [1, 0], [0, 2]],
  13: [[3, 3], [0, 0], [1, 0], [2, 1]],
  14: [[0, 3], [2, 2], [1, 0], [2, 0]],
  15: [[3, 0], [3, 2]],
  16: [[0, 0], [2, 3], [4, 1], [4, 2]],
  17: [[1, 2], [2, 4], [3, 4], [0, 2]],
  18: [[1, 3], [0, 3], [3, 0], [0, 2]],
  19: [[1, 1], [0, 1], [0, 4], [1, 0], [0, 0]],
  20: [[1, 2], [1, 1], [2, 3], [2, 2]],
  21: [[3, 1], [1, 3]],
  22: [[0, 3]],
  23: [[1, 0], [0, 3]],
  24: [[2, 4], [1, 1]],
  25: [[0, 3], [1, 3]],
  26: [[0, 3], [3, 0], [3, 1], [0, 2]],
  27: [[0, 2], [0, 1], [0, 3], [0, 0]],
  28: [[1, 4], [0, 4]],
  29: [[1, 2], [3, 2], [4, 0], [0, 0]],
  30: [[1, 1], [0, 0], [0, 1], [5, 2]],
  31: [[1, 2], [3, 1]],
  32: [[3, 1], [3, 2], [2, 0], [0, 3]],
  33: [[4, 3], [3, 3], [2, 3], [1, 1]],
  34: [[4, 0], [0, 2], [1, 2], [4, 1], [3, 3]],
  35: [[0, 1], [2, 2], [5, 0], [3, 3]],
  36: [[0, 0], [0, 4], [2, 2], [3, 3]],
  37: [[0, 0], [3, 2], [4, 0], [3, 0]],
  38: [[5, 2], [2, 3], [3, 1], [0, 0]],
  39: [[3, 1], [0, 3], [2, 1], [1, 1]],
  40: [[0, 0], [4, 2], [1, 2], [3, 2]],
  41: [[1, 1], [0, 3], [1, 2], [4, 0]],
  42: [[0, 3], [2, 1], [0, 4], [0, 0], [0, 2]],
  43: [[0, 0], [5, 0], [3, 3], [0, 1]],
  44: [[1, 3], [0, 0], [0, 1]],
  45: [[0, 3], [1, 3], [0, 2], [5, 2]],
  46: [[5, 0], [1, 1], [5, 1], [1, 0]],
  47: [[6, 3], [6, 2], [0, 3], [6, 0]],
  48: [[3, 1], [2, 3], [4, 1], [3, 3]],
  49: [[3, 4], [2, 0], [1, 3], [1, 1], [1, 0], [5, 4]],
  50: [[0, 2], [6, 2], [2, 3], [0, 1]],
  51: [[0, 0], [4, 2], [1, 2], [3, 2]],
  52: [[0, 3], [1, 2], [1, 3], [4, 2], [2, 2]],
  53: [[3, 3], [0, 0]],
  54: [[3, 2], [2, 2], [0, 3], [1, 1]],
  55: [[4, 0]],
  56: [[5, 3], [0, 0], [1, 2]],
  57: [[2, 3], [2, 2], [2, 0], [2, 1]],
  58: [[1, 2], [4, 1], [3, 3], [0, 0]],
  59: [[0, 0], [0, 2], [4, 1], [3, 0], [0, 1], [4, 2]],
  60: [[1, 0], [5, 1], [1, 3], [4, 1]],
  61: [[0, 4], [0, 3], [5, 3], [3, 2]],
  62: [[0, 1], [4, 4], [2, 3]],
  63: [[2, 2], [3, 0], [4, 0], [3, 2]],
  64: [[3, 0], [3, 4], [1, 1], [0, 2], [3, 3]],
  65: [[0, 0], [0, 1]],
  66: [[0, 1], [0, 2], [4, 0], [0, 3]],
  67: [[4, 4]],
  68: [[2, 0], [1, 1], [4, 0]],
  69: [[0, 0], [0, 1], [0, 2], [0, 3]],
  70: [[3, 3], [0, 1], [0, 0], [3, 0]],
  71: [[3, 4], [0, 4], [2, 0], [3, 3], [0, 3], [5, 0]],
  72: [[2, 1], [5, 3], [2, 0], [5, 2]],
  73: [[1, 5], [3, 0], [0, 0], [2, 5]],
  74: [[1, 4], [2, 3], [2, 4]],
  75: [[3, 2], [1, 3], [1, 1], [3, 0]],
  76: [[3, 3], [0, 3], [0, 2], [2, 0], [1, 0]],
  77: [[0, 0], [3, 2]],
  78: [[1, 2], [1, 3], [5, 2], [5, 3]],
  79: [[0, 0]],
  80: [[4, 1], [5, 2], [1, 2]],
  81: [[2, 2], [2, 1], [2, 3], [2, 0]],
  82: [[6, 1], [0, 2], [6, 3], [6, 0]],
  83: [[3, 0], [2, 0], [2, 4], [5, 0], [0, 0], [1, 0]],
  84: [[1, 2], [2, 2], [1, 3], [2, 3]],
  85: [[4, 4], [4, 0], [4, 3], [2, 5]],
  86: [[2, 1], [0, 0], [0, 1]],
  87: [[2, 0], [3, 0], [1, 2], [4, 0]],
  88: [[1, 0], [0, 0], [2, 0], [3, 4], [4, 2]],
  89: [[0, 0], [3, 3]],
  90: [[3, 1], [3, 2], [4, 1], [2, 0]],
  91: [[0, 0]],
  92: [[4, 3], [5, 2], [5, 3]],
  93: [[0, 3], [0, 0], [0, 2], [0, 1]],
  94: [[3, 0], [2, 1], [4, 2], [1, 1]],
  95: [[0, 0], [3, 1], [4, 1], [2, 4], [0, 1], [2, 1]],
  96: [[2, 3], [0, 2], [1, 1], [0, 3]],
  97: [[0, 5], [4, 0], [4, 5], [0, 4]],
  98: [[5, 3], [3, 2], [0, 2]],
  99: [[3, 1], [3, 2], [0, 2], [4, 3]],
  100: [[4, 2], [3, 3], [3, 2], [2, 3], [0, 0]],
  101: [[0, 0], [3, 2]],
  102: [[1, 2], [1, 1], [3, 0], [5, 1]],
  103: [[0, 0]],
  104: [[0, 1], [0, 0], [5, 0]],
  105: [[0, 0], [0, 1], [0, 2], [0, 3]],
  106: [[6, 2], [0, 0], [0, 1], [6, 1]],
  107: [[0, 0], [0, 1], [4, 1], [2, 4], [1, 0], [2, 2]],
  108: [[4, 2], [2, 0], [0, 3], [4, 3]],
  109: [[0, 3], [5, 1], [1, 0], [0, 2]],
  110: [[4, 1], [0, 3], [2, 4]],
  111: [[1, 2], [1, 3], [0, 0], [4, 1]],
  112: [[0, 3], [4, 0], [4, 2], [4, 1], [0, 0]],
  113: [[1, 2], [4, 1]],
  114: [[0, 0], [1, 0], [1, 1], [0, 1]],
  115: [[0, 4]],
  116: [[4, 2], [0, 3], [3, 3]],
  117: [[0, 0], [0, 1], [0, 2], [0, 3]],
  118: [[2, 2], [6, 1], [0, 0], [0, 3]],
  119: [[4, 1], [2, 0], [2, 3], [5, 4], [4, 2], [2, 2]],
  120: [[1, 1], [2, 3], [0, 0], [2, 1]],
  121: [[3, 2], [3, 5], [0, 3], [4, 4]],
  122: [[0, 0], [0, 1], [4, 4]],
  123: [[3, 3], [4, 3], [0, 1], [3, 1]],
  124: [[0, 2], [0, 1], [1, 3], [3, 4], [0, 0]],
  125: [[0, 3], [0, 0]],
  126: [[3, 0], [5, 3], [2, 0], [2, 3]],
  127: [[0, 0]],
  128: [[0, 0], [1, 2], [3, 0]],
  129: [[2, 3], [0, 0], [0, 1], [2, 2]],
  130: [[0, 1], [3, 3], [6, 1], [5, 1]],
  131: [[5, 4], [1, 2], [0, 0], [4, 0], [3, 3], [0, 1]],
  132: [[2, 3], [5, 3], [0, 1], [3, 3]],
  133: [[0, 0], [0, 1], [1, 2], [5, 3]],
  134: [[5, 2], [4, 3], [5, 0]],
  135: [[0, 0], [3, 2], [3, 0], [4, 0]],
  136: [[0, 0], [4, 0], [1, 2], [2, 2], [1, 0]],
  137: [[4, 1], [1, 2]],
  138: [[2, 2], [3, 1], [1, 0], [2, 3]],
  139: [[0, 0]],
  140: [[2, 3], [1, 3], [1, 0]],
  141: [[0, 0], [0, 1], [0, 2], [0, 3]],
  142: [[5, 0], [5, 3], [0, 3], [2, 0]],
  143: [[1, 0], [0, 4], [3, 1], [1, 2], [5, 0], [5, 1]],
  144: [[4, 2], [1, 3], [5, 0], [2, 3]],
  145: [[3, 5], [2, 3], [0, 2], [1, 0]],
  146: [[5, 2], [1, 3], [2, 2]],
  147: [[0, 1], [0, 0], [3, 0], [3, 3]],
  148: [[1, 3], [1, 1], [3, 3], [1, 4], [4, 3]],
  149: [[0, 0], [4, 0]],
  150: [[3, 3], [0, 3], [2, 3], [1, 3]],
  151: [[0, 0]],
  152: [[1, 3], [3, 1], [0, 3]],
  153: [[4, 2], [2, 0], [4, 3], [2, 1]],
  154: [[2, 1], [2, 0], [5, 2], [5, 3]],
  155: [[3, 0], [3, 3], [0, 0], [0, 1], [2, 3], [1, 3]],
  156: [[0, 3], [3, 3], [5, 3], [3, 0]],
  157: [[2, 2], [0, 0], [0, 1], [2, 5]],
  158: [[3, 0], [2, 0], [4, 3]],
  159: [[0, 0], [0, 1], [4, 3], [0, 2]],
  160: [[0, 3], [0, 0], [0, 4], [2, 2], [0, 1]],
  161: [[0, 2], [0, 1]],
  162: [[1, 3], [0, 0], [2, 3], [1, 0]],
  163: [[0, 0]],
  164: [[0, 1], [0, 2], [3, 3]],
  165: [[0, 3], [0, 2], [2, 1], [2, 0]],
  166: [[0, 0], [0, 1], [4, 2], [6, 3]],
  167: [[0, 2], [0, 0], [1, 4], [0, 1], [4, 3], [2, 2]],
  168: [[0, 0], [3, 0], [1, 0], [4, 2]],
  169: [[5, 0], [0, 0], [4, 5], [5, 5]],
  170: [[3, 0], [2, 0], [0, 1]],
  171: [[1, 3], [4, 2], [3, 2], [0, 3]],
  172: [[0, 1], [1, 3], [1, 4], [4, 2], [0, 0]],
  173: [[0, 0], [0, 1]],
  174: [[0, 3], [3, 3], [4, 3], [1, 1]],
  175: [[0, 4]],
  176: [[3, 3], [2, 0], [2, 3]],
  177: [[0, 2], [0, 3], [0, 1], [0, 0]],
  178: [[2, 3], [0, 0], [4, 3], [6, 0]],
  179: [[5, 3], [1, 4], [0, 2], [0, 1], [5, 2], [2, 0]],
  180: [[2, 3], [5, 0], [4, 0], [1, 1]],
  181: [[4, 1], [3, 1], [3, 2], [0, 4]],
  182: [[0, 3], [0, 0], [2, 2]],
  183: [[2, 0], [1, 2], [3, 0], [4, 0]],
  184: [[2, 3], [0, 2], [4, 3], [0, 4], [4, 4]],
  185: [[0, 2], [0, 1]],
  186: [[1, 3], [3, 1], [2, 3], [4, 1]],
  187: [[0, 0]],
  188: [[1, 1], [4, 1], [2, 0]],
  189: [[0, 0], [0, 1], [0, 2], [0, 3]],
  190: [[1, 3], [0, 3], [4, 3], [5, 1]],
  191: [[4, 1], [3, 0], [3, 1], [2, 1], [5, 3], [2, 0]],
  192: [[0, 3], [2, 0], [5, 2], [5, 1]],
  193: [[0, 3], [0, 2], [5, 3], [5, 4]],
  194: [[2, 4], [1, 0], [2, 2]],
  195: [[0, 3], [3, 1], [4, 3], [3, 3]],
  196: [[0, 3], [1, 1], [3, 4], [0, 4], [4, 2]],
  197: [[2, 3], [0, 0]],
  198: [[4, 3], [5, 0], [5, 3], [0, 0]],
  199: [[0, 0]],
  200: [[0, 0], [0, 1], [4, 2]],
};

// =====================================================
// LEVELS 1-9: Tutorial levels (no blocked cells)
// =====================================================

const LEVEL_1: Level = {
  id: 1,
  name: 'First Steps',
  gridRows: 2,
  gridCols: 2,
  activeCells: rect(2, 2),
  lockedCells: [],
  requiredShapes: [{ shape: TETROMINO_O, required: 1, placed: 0 }],
  difficulty: 1,
};

const LEVEL_2: Level = {
  id: 2,
  name: 'Two Halves',
  gridRows: 2,
  gridCols: 2,
  activeCells: rect(2, 2),
  lockedCells: [],
  requiredShapes: [{ shape: DOMINO, required: 2, placed: 0 }],
  difficulty: 1,
};

const LEVEL_3: Level = {
  id: 3,
  name: 'Domino Line',
  gridRows: 2,
  gridCols: 3,
  activeCells: rect(2, 3),
  lockedCells: [],
  requiredShapes: [{ shape: DOMINO, required: 3, placed: 0 }],
  difficulty: 1,
};

const LEVEL_4: Level = {
  id: 4,
  name: 'Twin Squares',
  gridRows: 2,
  gridCols: 4,
  activeCells: rect(2, 4),
  lockedCells: [],
  requiredShapes: [{ shape: TETROMINO_O, required: 2, placed: 0 }],
  difficulty: 1,
};

const LEVEL_5: Level = {
  id: 5,
  name: 'Three in Row',
  gridRows: 2,
  gridCols: 3,
  activeCells: rect(2, 3),
  lockedCells: [],
  requiredShapes: [{ shape: TRIOMINO_I, required: 2, placed: 0 }],
  difficulty: 1,
};

const LEVEL_6: Level = {
  id: 6,
  name: 'Corner Piece',
  gridRows: 2,
  gridCols: 2,
  activeCells: [[0, 0], [1, 0], [1, 1]],
  lockedCells: [],
  requiredShapes: [{ shape: TRIOMINO_L, required: 1, placed: 0 }],
  difficulty: 1,
};

const LEVEL_7: Level = {
  id: 7,
  name: 'Two Corners',
  gridRows: 2,
  gridCols: 3,
  activeCells: rect(2, 3),
  lockedCells: [],
  requiredShapes: [{ shape: TRIOMINO_L, required: 2, placed: 0 }],
  difficulty: 1,
};

const LEVEL_8: Level = {
  id: 8,
  name: 'Long Block',
  gridRows: 1,
  gridCols: 4,
  activeCells: rect(1, 4),
  lockedCells: [],
  requiredShapes: [{ shape: TETROMINO_I, required: 1, placed: 0 }],
  difficulty: 1,
};

const LEVEL_9: Level = {
  id: 9,
  name: 'Domino Stack',
  gridRows: 4,
  gridCols: 2,
  activeCells: rect(4, 2),
  lockedCells: [],
  requiredShapes: [{ shape: DOMINO, required: 4, placed: 0 }],
  difficulty: 1,
};

// =====================================================
// LEVELS 10-50: Manually defined with verified blocked cells
// =====================================================

const LEVEL_10: Level = {
  id: 10,
  name: 'First Obstacle',
  gridRows: 3,
  gridCols: 4,
  activeCells: rect(3, 4),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[10],
  requiredShapes: [{ shape: DOMINO, required: 5, placed: 0 }],
  difficulty: 1,
};

const LEVEL_11: Level = {
  id: 11,
  name: 'Corner Block',
  gridRows: 3,
  gridCols: 4,
  activeCells: rect(3, 4),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[11],
  requiredShapes: [
    { shape: TRIOMINO_L, required: 3, placed: 0 },
    { shape: DOMINO, required: 1, placed: 0 },
  ],
  difficulty: 1,
};

const LEVEL_12: Level = {
  id: 12,
  name: 'Donut',
  gridRows: 4,
  gridCols: 4,
  activeCells: rect(4, 4),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[12],
  requiredShapes: [{ shape: TRIOMINO_L, required: 4, placed: 0 }],
  difficulty: 2,
};

const LEVEL_13: Level = {
  id: 13,
  name: 'Edge Block',
  gridRows: 4,
  gridCols: 4,
  activeCells: rect(4, 4),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[13],
  requiredShapes: [{ shape: TRIOMINO_L, required: 4, placed: 0 }],
  difficulty: 2,
};

const LEVEL_14: Level = {
  id: 14,
  name: 'Scattered',
  gridRows: 4,
  gridCols: 4,
  activeCells: rect(4, 4),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[14],
  requiredShapes: [{ shape: TETROMINO_L, required: 3, placed: 0 }],
  difficulty: 2,
};

const LEVEL_15: Level = {
  id: 15,
  name: 'Corner Chaos',
  gridRows: 4,
  gridCols: 4,
  activeCells: rect(4, 4),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[15],
  requiredShapes: [
    { shape: TETROMINO_T, required: 2, placed: 0 },
    { shape: TRIOMINO_L, required: 2, placed: 0 },
  ],
  difficulty: 2,
};

const LEVEL_16: Level = {
  id: 16,
  name: 'Split Path',
  gridRows: 5,
  gridCols: 4,
  activeCells: rect(5, 4),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[16],
  requiredShapes: [
    { shape: TETROMINO_L, required: 2, placed: 0 },
    { shape: TETROMINO_J, required: 2, placed: 0 },
  ],
  difficulty: 2,
};

const LEVEL_17: Level = {
  id: 17,
  name: 'Cross Roads',
  gridRows: 4,
  gridCols: 5,
  activeCells: rect(4, 5),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[17],
  requiredShapes: [
    { shape: TETROMINO_O, required: 2, placed: 0 },
    { shape: TETROMINO_T, required: 2, placed: 0 },
  ],
  difficulty: 2,
};

const LEVEL_18: Level = {
  id: 18,
  name: 'Checkers',
  gridRows: 5,
  gridCols: 4,
  activeCells: rect(5, 4),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[18],
  requiredShapes: [
    { shape: TETROMINO_S, required: 2, placed: 0 },
    { shape: TETROMINO_Z, required: 2, placed: 0 },
  ],
  difficulty: 2,
};

const LEVEL_19: Level = {
  id: 19,
  name: 'Bullseye',
  gridRows: 5,
  gridCols: 5,
  activeCells: rect(5, 5),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[19],
  requiredShapes: [
    { shape: TETROMINO_L, required: 4, placed: 0 },
    { shape: TETROMINO_O, required: 1, placed: 0 },
  ],
  difficulty: 2,
};

const LEVEL_20: Level = {
  id: 20,
  name: 'Zigzag',
  gridRows: 5,
  gridCols: 4,
  activeCells: rect(5, 4),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[20],
  requiredShapes: [
    { shape: TETROMINO_L, required: 2, placed: 0 },
    { shape: TETROMINO_O, required: 2, placed: 0 },
  ],
  difficulty: 2,
};

const LEVEL_21: Level = {
  id: 21,
  name: 'Side Step',
  gridRows: 5,
  gridCols: 4,
  activeCells: rect(5, 4),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[21],
  requiredShapes: [
    { shape: TRIOMINO_L, required: 4, placed: 0 },
    { shape: DOMINO, required: 3, placed: 0 },
  ],
  difficulty: 2,
};

const LEVEL_22: Level = {
  id: 22,
  name: 'Corner Cut',
  gridRows: 4,
  gridCols: 4,
  activeCells: rect(4, 4),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[22],
  requiredShapes: [
    { shape: TRIOMINO_L, required: 3, placed: 0 },
    { shape: TRIOMINO_I, required: 2, placed: 0 },
  ],
  difficulty: 2,
};

const LEVEL_23: Level = {
  id: 23,
  name: 'Top Heavy',
  gridRows: 5,
  gridCols: 4,
  activeCells: rect(5, 4),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[23],
  requiredShapes: [
    { shape: TRIOMINO_L, required: 4, placed: 0 },
    { shape: TETROMINO_O, required: 1, placed: 0 },
    { shape: DOMINO, required: 1, placed: 0 },
  ],
  difficulty: 2,
};

const LEVEL_24: Level = {
  id: 24,
  name: 'Center Piece',
  gridRows: 4,
  gridCols: 5,
  activeCells: rect(4, 5),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[24],
  requiredShapes: [
    { shape: TRIOMINO_L, required: 4, placed: 0 },
    { shape: TETROMINO_O, required: 1, placed: 0 },
    { shape: DOMINO, required: 1, placed: 0 },
  ],
  difficulty: 2,
};

const LEVEL_25: Level = {
  id: 25,
  name: 'Corner Trap',
  gridRows: 5,
  gridCols: 4,
  activeCells: rect(5, 4),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[25],
  requiredShapes: [
    { shape: TRIOMINO_L, required: 4, placed: 0 },
    { shape: DOMINO, required: 3, placed: 0 },
  ],
  difficulty: 2,
};

const LEVEL_26: Level = {
  id: 26,
  name: 'Edge Guard',
  gridRows: 5,
  gridCols: 4,
  activeCells: rect(5, 4),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[26],
  requiredShapes: [
    { shape: TETROMINO_L, required: 2, placed: 0 },
    { shape: TETROMINO_O, required: 2, placed: 0 },
  ],
  difficulty: 2,
};

const LEVEL_27: Level = {
  id: 27,
  name: 'Mid Block',
  gridRows: 5,
  gridCols: 4,
  activeCells: rect(5, 4),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[27],
  requiredShapes: [
    { shape: TETROMINO_O, required: 2, placed: 0 },
    { shape: TETROMINO_L, required: 2, placed: 0 },
  ],
  difficulty: 2,
};

const LEVEL_28: Level = {
  id: 28,
  name: 'Narrow Pass',
  gridRows: 4,
  gridCols: 5,
  activeCells: rect(4, 5),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[28],
  requiredShapes: [
    { shape: TRIOMINO_L, required: 4, placed: 0 },
    { shape: TRIOMINO_I, required: 2, placed: 0 },
  ],
  difficulty: 2,
};

const LEVEL_29: Level = {
  id: 29,
  name: 'Dot Matrix',
  gridRows: 5,
  gridCols: 4,
  activeCells: rect(5, 4),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[29],
  requiredShapes: [
    { shape: TETROMINO_L, required: 2, placed: 0 },
    { shape: TETROMINO_T, required: 2, placed: 0 },
  ],
  difficulty: 2,
};

const LEVEL_30: Level = {
  id: 30,
  name: 'Split Level',
  gridRows: 6,
  gridCols: 4,
  activeCells: rect(6, 4),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[30],
  requiredShapes: [
    { shape: TETROMINO_L, required: 2, placed: 0 },
    { shape: TETROMINO_O, required: 1, placed: 0 },
    { shape: TETROMINO_T, required: 2, placed: 0 },
  ],
  difficulty: 2,
};

const LEVEL_31: Level = {
  id: 31,
  name: 'Top Block',
  gridRows: 5,
  gridCols: 4,
  activeCells: rect(5, 4),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[31],
  requiredShapes: [
    { shape: TRIOMINO_L, required: 2, placed: 0 },
    { shape: TRIOMINO_I, required: 2, placed: 0 },
    { shape: DOMINO, required: 3, placed: 0 },
  ],
  difficulty: 2,
};

const LEVEL_32: Level = {
  id: 32,
  name: 'Base Camp',
  gridRows: 5,
  gridCols: 4,
  activeCells: rect(5, 4),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[32],
  requiredShapes: [
    { shape: TETROMINO_L, required: 2, placed: 0 },
    { shape: TETROMINO_O, required: 1, placed: 0 },
    { shape: TETROMINO_T, required: 1, placed: 0 },
  ],
  difficulty: 2,
};

const LEVEL_33: Level = {
  id: 33,
  name: 'Side Notch',
  gridRows: 6,
  gridCols: 4,
  activeCells: rect(6, 4),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[33],
  requiredShapes: [
    { shape: TETROMINO_L, required: 2, placed: 0 },
    { shape: TETROMINO_O, required: 1, placed: 0 },
    { shape: TETROMINO_T, required: 2, placed: 0 },
  ],
  difficulty: 2,
};

const LEVEL_34: Level = {
  id: 34,
  name: 'Five Point',
  gridRows: 5,
  gridCols: 5,
  activeCells: rect(5, 5),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[34],
  requiredShapes: [
    { shape: TETROMINO_L, required: 2, placed: 0 },
    { shape: TETROMINO_O, required: 1, placed: 0 },
    { shape: TETROMINO_T, required: 2, placed: 0 },
  ],
  difficulty: 2,
};

const LEVEL_35: Level = {
  id: 35,
  name: 'Inner Wall',
  gridRows: 6,
  gridCols: 4,
  activeCells: rect(6, 4),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[35],
  requiredShapes: [
    { shape: TETROMINO_L, required: 2, placed: 0 },
    { shape: TETROMINO_O, required: 1, placed: 0 },
    { shape: TETROMINO_T, required: 2, placed: 0 },
  ],
  difficulty: 2,
};

const LEVEL_36: Level = {
  id: 36,
  name: 'Edge Case',
  gridRows: 5,
  gridCols: 5,
  activeCells: rect(5, 5),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[36],
  requiredShapes: [
    { shape: TRIOMINO_L, required: 3, placed: 0 },
    { shape: TRIOMINO_I, required: 2, placed: 0 },
    { shape: DOMINO, required: 3, placed: 0 },
  ],
  difficulty: 2,
};

const LEVEL_37: Level = {
  id: 37,
  name: 'Column Block',
  gridRows: 6,
  gridCols: 4,
  activeCells: rect(6, 4),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[37],
  requiredShapes: [
    { shape: TETROMINO_S, required: 2, placed: 0 },
    { shape: TETROMINO_Z, required: 2, placed: 0 },
    { shape: TETROMINO_O, required: 1, placed: 0 },
  ],
  difficulty: 3,
};

const LEVEL_38: Level = {
  id: 38,
  name: 'Scattered',
  gridRows: 6,
  gridCols: 4,
  activeCells: rect(6, 4),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[38],
  requiredShapes: [
    { shape: TETROMINO_J, required: 2, placed: 0 },
    { shape: TETROMINO_L, required: 2, placed: 0 },
    { shape: TETROMINO_O, required: 1, placed: 0 },
  ],
  difficulty: 3,
};

const LEVEL_39: Level = {
  id: 39,
  name: 'Center Split',
  gridRows: 6,
  gridCols: 4,
  activeCells: rect(6, 4),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[39],
  requiredShapes: [
    { shape: TETROMINO_I, required: 2, placed: 0 },
    { shape: TETROMINO_T, required: 2, placed: 0 },
    { shape: TETROMINO_O, required: 1, placed: 0 },
  ],
  difficulty: 3,
};

const LEVEL_40: Level = {
  id: 40,
  name: 'U-Turn',
  gridRows: 6,
  gridCols: 4,
  activeCells: rect(6, 4),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[40],
  requiredShapes: [
    { shape: TETROMINO_Z, required: 2, placed: 0 },
    { shape: TETROMINO_J, required: 2, placed: 0 },
    { shape: TETROMINO_O, required: 1, placed: 0 },
  ],
  difficulty: 3,
};

const LEVEL_41: Level = {
  id: 41,
  name: 'Box In',
  gridRows: 6,
  gridCols: 4,
  activeCells: rect(6, 4),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[41],
  requiredShapes: [
    { shape: TETROMINO_S, required: 2, placed: 0 },
    { shape: TETROMINO_L, required: 2, placed: 0 },
    { shape: TETROMINO_T, required: 1, placed: 0 },
  ],
  difficulty: 3,
};

const LEVEL_42: Level = {
  id: 42,
  name: 'Step Up',
  gridRows: 5,
  gridCols: 5,
  activeCells: rect(5, 5),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[42],
  requiredShapes: [
    { shape: TETROMINO_J, required: 2, placed: 0 },
    { shape: TETROMINO_Z, required: 2, placed: 0 },
    { shape: TETROMINO_T, required: 1, placed: 0 },
  ],
  difficulty: 3,
};

const LEVEL_43: Level = {
  id: 43,
  name: 'Frame It',
  gridRows: 6,
  gridCols: 4,
  activeCells: rect(6, 4),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[43],
  requiredShapes: [
    { shape: TETROMINO_L, required: 2, placed: 0 },
    { shape: TETROMINO_S, required: 2, placed: 0 },
    { shape: TETROMINO_O, required: 1, placed: 0 },
  ],
  difficulty: 3,
};

const LEVEL_44: Level = {
  id: 44,
  name: 'T-Block',
  gridRows: 6,
  gridCols: 4,
  activeCells: rect(6, 4),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[44],
  requiredShapes: [
    { shape: TRIOMINO_L, required: 3, placed: 0 },
    { shape: TRIOMINO_I, required: 2, placed: 0 },
    { shape: DOMINO, required: 3, placed: 0 },
  ],
  difficulty: 3,
};

const LEVEL_45: Level = {
  id: 45,
  name: 'Big Hole',
  gridRows: 6,
  gridCols: 6,
  activeCells: rect(6, 6),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[45],
  requiredShapes: [
    { shape: TETROMINO_J, required: 3, placed: 0 },
    { shape: TETROMINO_L, required: 3, placed: 0 },
    { shape: TETROMINO_O, required: 2, placed: 0 },
  ],
  difficulty: 3,
};

const LEVEL_46: Level = {
  id: 46,
  name: 'Cross Out',
  gridRows: 6,
  gridCols: 4,
  activeCells: rect(6, 4),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[46],
  requiredShapes: [
    { shape: TETROMINO_I, required: 2, placed: 0 },
    { shape: TETROMINO_S, required: 2, placed: 0 },
    { shape: TETROMINO_O, required: 1, placed: 0 },
  ],
  difficulty: 3,
};

const LEVEL_47: Level = {
  id: 47,
  name: 'Long Way',
  gridRows: 7,
  gridCols: 4,
  activeCells: rect(7, 4),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[47],
  requiredShapes: [
    { shape: TETROMINO_Z, required: 2, placed: 0 },
    { shape: TETROMINO_T, required: 2, placed: 0 },
    { shape: TETROMINO_L, required: 2, placed: 0 },
  ],
  difficulty: 3,
};

const LEVEL_48: Level = {
  id: 48,
  name: 'Grid Lock',
  gridRows: 6,
  gridCols: 4,
  activeCells: rect(6, 4),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[48],
  requiredShapes: [
    { shape: TETROMINO_J, required: 2, placed: 0 },
    { shape: TETROMINO_S, required: 2, placed: 0 },
    { shape: TETROMINO_T, required: 1, placed: 0 },
  ],
  difficulty: 3,
};

const LEVEL_49: Level = {
  id: 49,
  name: 'Border Run',
  gridRows: 6,
  gridCols: 5,
  activeCells: rect(6, 5),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[49],
  requiredShapes: [
    { shape: TETROMINO_L, required: 2, placed: 0 },
    { shape: TETROMINO_Z, required: 2, placed: 0 },
    { shape: TETROMINO_J, required: 2, placed: 0 },
  ],
  difficulty: 3,
};

const LEVEL_50: Level = {
  id: 50,
  name: 'Final Push',
  gridRows: 7,
  gridCols: 4,
  activeCells: rect(7, 4),
  lockedCells: [],
  blockedCells: VERIFIED_BLOCKED[50],
  requiredShapes: [
    { shape: TETROMINO_S, required: 2, placed: 0 },
    { shape: TETROMINO_Z, required: 2, placed: 0 },
    { shape: TETROMINO_T, required: 2, placed: 0 },
  ],
  difficulty: 3,
};

// =====================================================
// LEVELS 51-200: Generated with verified blocked cells
// All patterns have 2-5 different shape types
// =====================================================

// Pattern configurations for generated levels - 50 unique combinations
const GENERATED_PATTERNS = [
  // Group 1: L + O combinations (2 shapes)
  { rows: 5, cols: 4, blockCount: 4, shapes: [
    { shape: TETROMINO_L, required: 2, placed: 0 },
    { shape: TETROMINO_O, required: 2, placed: 0 },
  ]},
  // Group 2: S + Z combinations (2 shapes)
  { rows: 5, cols: 4, blockCount: 4, shapes: [
    { shape: TETROMINO_S, required: 2, placed: 0 },
    { shape: TETROMINO_Z, required: 2, placed: 0 },
  ]},
  // Group 3: J + T combinations (2 shapes)
  { rows: 5, cols: 4, blockCount: 4, shapes: [
    { shape: TETROMINO_J, required: 2, placed: 0 },
    { shape: TETROMINO_T, required: 2, placed: 0 },
  ]},
  // Group 4: L + J + O (3 shapes)
  { rows: 5, cols: 5, blockCount: 5, shapes: [
    { shape: TETROMINO_L, required: 2, placed: 0 },
    { shape: TETROMINO_J, required: 2, placed: 0 },
    { shape: TETROMINO_O, required: 1, placed: 0 },
  ]},
  // Group 5: Triominos (3 shapes)
  { rows: 5, cols: 4, blockCount: 2, shapes: [
    { shape: TRIOMINO_L, required: 3, placed: 0 },
    { shape: TRIOMINO_I, required: 2, placed: 0 },
    { shape: DOMINO, required: 1, placed: 0 },
  ]},
  // Group 6: S + T + O (3 shapes)
  { rows: 6, cols: 4, blockCount: 4, shapes: [
    { shape: TETROMINO_S, required: 2, placed: 0 },
    { shape: TETROMINO_T, required: 1, placed: 0 },
    { shape: TETROMINO_O, required: 2, placed: 0 },
  ]},
  // Group 7: Z + L + I (3 shapes)
  { rows: 5, cols: 5, blockCount: 1, shapes: [
    { shape: TETROMINO_Z, required: 2, placed: 0 },
    { shape: TETROMINO_L, required: 2, placed: 0 },
    { shape: TETROMINO_I, required: 2, placed: 0 },
  ]},
  // Group 8: Mixed triominos (3 shapes)
  { rows: 6, cols: 4, blockCount: 3, shapes: [
    { shape: TRIOMINO_L, required: 3, placed: 0 },
    { shape: TRIOMINO_I, required: 2, placed: 0 },
    { shape: DOMINO, required: 3, placed: 0 },
  ]},
  // Group 9: J + S + T (3 shapes)
  { rows: 5, cols: 4, blockCount: 4, shapes: [
    { shape: TETROMINO_J, required: 2, placed: 0 },
    { shape: TETROMINO_S, required: 1, placed: 0 },
    { shape: TETROMINO_T, required: 1, placed: 0 },
  ]},
  // Group 10: L + Z + O (3 shapes)
  { rows: 7, cols: 4, blockCount: 4, shapes: [
    { shape: TETROMINO_L, required: 2, placed: 0 },
    { shape: TETROMINO_Z, required: 2, placed: 0 },
    { shape: TETROMINO_O, required: 2, placed: 0 },
  ]},
  // Group 11: All tetrominos mix 1 (4 shapes)
  { rows: 6, cols: 5, blockCount: 6, shapes: [
    { shape: TETROMINO_L, required: 2, placed: 0 },
    { shape: TETROMINO_T, required: 2, placed: 0 },
    { shape: TETROMINO_S, required: 1, placed: 0 },
    { shape: TETROMINO_O, required: 1, placed: 0 },
  ]},
  // Group 12: Dominoes + Triominos (3 shapes)
  { rows: 6, cols: 4, blockCount: 4, shapes: [
    { shape: DOMINO, required: 4, placed: 0 },
    { shape: TRIOMINO_L, required: 2, placed: 0 },
    { shape: TRIOMINO_I, required: 2, placed: 0 },
  ]},
  // Group 13: J + O + I (3 shapes)
  { rows: 6, cols: 6, blockCount: 4, shapes: [
    { shape: TETROMINO_J, required: 3, placed: 0 },
    { shape: TETROMINO_O, required: 2, placed: 0 },
    { shape: TETROMINO_I, required: 3, placed: 0 },
  ]},
  // Group 14: L + Triominos (3 shapes)
  { rows: 6, cols: 5, blockCount: 3, shapes: [
    { shape: TETROMINO_L, required: 3, placed: 0 },
    { shape: TRIOMINO_L, required: 3, placed: 0 },
    { shape: DOMINO, required: 3, placed: 0 },
  ]},
  // Group 15: S + Z + T (3 shapes)
  { rows: 5, cols: 5, blockCount: 4, shapes: [
    { shape: TETROMINO_S, required: 2, placed: 0 },
    { shape: TETROMINO_Z, required: 2, placed: 0 },
    { shape: TETROMINO_T, required: 1, placed: 0 },
  ]},
  // Group 16: J + L mirror (2 shapes)
  { rows: 5, cols: 4, blockCount: 4, shapes: [
    { shape: TETROMINO_J, required: 2, placed: 0 },
    { shape: TETROMINO_L, required: 2, placed: 0 },
  ]},
  // Group 17: I + O (2 shapes)
  { rows: 5, cols: 4, blockCount: 4, shapes: [
    { shape: TETROMINO_I, required: 2, placed: 0 },
    { shape: TETROMINO_O, required: 2, placed: 0 },
  ]},
  // Group 18: T + O + S (3 shapes)
  { rows: 6, cols: 4, blockCount: 4, shapes: [
    { shape: TETROMINO_T, required: 2, placed: 0 },
    { shape: TETROMINO_O, required: 2, placed: 0 },
    { shape: TETROMINO_S, required: 1, placed: 0 },
  ]},
  // Group 19: J + Z + I (3 shapes)
  { rows: 5, cols: 5, blockCount: 5, shapes: [
    { shape: TETROMINO_J, required: 2, placed: 0 },
    { shape: TETROMINO_Z, required: 2, placed: 0 },
    { shape: TETROMINO_I, required: 1, placed: 0 },
  ]},
  // Group 20: L + S + O (3 shapes)
  { rows: 6, cols: 5, blockCount: 2, shapes: [
    { shape: TETROMINO_L, required: 3, placed: 0 },
    { shape: TETROMINO_S, required: 2, placed: 0 },
    { shape: TETROMINO_O, required: 2, placed: 0 },
  ]},
  // Group 21: 4 shapes mix 1
  { rows: 6, cols: 5, blockCount: 6, shapes: [
    { shape: TETROMINO_J, required: 2, placed: 0 },
    { shape: TETROMINO_Z, required: 2, placed: 0 },
    { shape: TETROMINO_T, required: 1, placed: 0 },
    { shape: TETROMINO_O, required: 1, placed: 0 },
  ]},
  // Group 22: 4 shapes mix 2
  { rows: 6, cols: 4, blockCount: 4, shapes: [
    { shape: TETROMINO_L, required: 2, placed: 0 },
    { shape: TETROMINO_S, required: 1, placed: 0 },
    { shape: TETROMINO_Z, required: 1, placed: 0 },
    { shape: TETROMINO_T, required: 1, placed: 0 },
  ]},
  // Group 23: Small pieces (3 shapes)
  { rows: 5, cols: 4, blockCount: 2, shapes: [
    { shape: TRIOMINO_L, required: 4, placed: 0 },
    { shape: DOMINO, required: 2, placed: 0 },
    { shape: MONOMINO, required: 2, placed: 0 },
  ]},
  // Group 24: I + T (2 shapes)
  { rows: 6, cols: 4, blockCount: 4, shapes: [
    { shape: TETROMINO_I, required: 3, placed: 0 },
    { shape: TETROMINO_T, required: 2, placed: 0 },
  ]},
  // Group 25: J + O (2 shapes)
  { rows: 5, cols: 4, blockCount: 4, shapes: [
    { shape: TETROMINO_J, required: 2, placed: 0 },
    { shape: TETROMINO_O, required: 2, placed: 0 },
  ]},
  // Group 26: Z + O + I (3 shapes)
  { rows: 6, cols: 4, blockCount: 4, shapes: [
    { shape: TETROMINO_Z, required: 2, placed: 0 },
    { shape: TETROMINO_O, required: 2, placed: 0 },
    { shape: TETROMINO_I, required: 1, placed: 0 },
  ]},
  // Group 27: L + J + T (3 shapes)
  { rows: 5, cols: 5, blockCount: 4, shapes: [
    { shape: TETROMINO_L, required: 2, placed: 0 },
    { shape: TETROMINO_J, required: 2, placed: 0 },
    { shape: TETROMINO_T, required: 1, placed: 0 },
  ]},
  // Group 28: S + O (2 shapes)
  { rows: 5, cols: 4, blockCount: 4, shapes: [
    { shape: TETROMINO_S, required: 2, placed: 0 },
    { shape: TETROMINO_O, required: 2, placed: 0 },
  ]},
  // Group 29: Triomino + Domino (2 shapes)
  { rows: 5, cols: 4, blockCount: 2, shapes: [
    { shape: TRIOMINO_L, required: 4, placed: 0 },
    { shape: DOMINO, required: 3, placed: 0 },
  ]},
  // Group 30: 4 shapes - J,L,S,Z
  { rows: 6, cols: 5, blockCount: 6, shapes: [
    { shape: TETROMINO_J, required: 2, placed: 0 },
    { shape: TETROMINO_L, required: 2, placed: 0 },
    { shape: TETROMINO_S, required: 1, placed: 0 },
    { shape: TETROMINO_Z, required: 1, placed: 0 },
  ]},
  // Group 31: Z + T (2 shapes)
  { rows: 5, cols: 4, blockCount: 4, shapes: [
    { shape: TETROMINO_Z, required: 2, placed: 0 },
    { shape: TETROMINO_T, required: 2, placed: 0 },
  ]},
  // Group 32: L + I + T (3 shapes)
  { rows: 6, cols: 5, blockCount: 2, shapes: [
    { shape: TETROMINO_L, required: 3, placed: 0 },
    { shape: TETROMINO_I, required: 2, placed: 0 },
    { shape: TETROMINO_T, required: 2, placed: 0 },
  ]},
  // Group 33: J + S (2 shapes)
  { rows: 5, cols: 4, blockCount: 4, shapes: [
    { shape: TETROMINO_J, required: 2, placed: 0 },
    { shape: TETROMINO_S, required: 2, placed: 0 },
  ]},
  // Group 34: O + T + Z (3 shapes)
  { rows: 5, cols: 5, blockCount: 4, shapes: [
    { shape: TETROMINO_O, required: 2, placed: 0 },
    { shape: TETROMINO_T, required: 2, placed: 0 },
    { shape: TETROMINO_Z, required: 1, placed: 0 },
  ]},
  // Group 35: Small + Large mix (3 shapes)
  { rows: 6, cols: 4, blockCount: 4, shapes: [
    { shape: TETROMINO_L, required: 2, placed: 0 },
    { shape: TRIOMINO_L, required: 2, placed: 0 },
    { shape: DOMINO, required: 4, placed: 0 },
  ]},
  // Group 36: 5 shapes mix
  { rows: 6, cols: 5, blockCount: 6, shapes: [
    { shape: TETROMINO_L, required: 1, placed: 0 },
    { shape: TETROMINO_J, required: 1, placed: 0 },
    { shape: TETROMINO_T, required: 1, placed: 0 },
    { shape: TETROMINO_S, required: 1, placed: 0 },
    { shape: TETROMINO_O, required: 2, placed: 0 },
  ]},
  // Group 37: L + Z (2 shapes)
  { rows: 5, cols: 4, blockCount: 4, shapes: [
    { shape: TETROMINO_L, required: 2, placed: 0 },
    { shape: TETROMINO_Z, required: 2, placed: 0 },
  ]},
  // Group 38: J + I + O (3 shapes)
  { rows: 6, cols: 4, blockCount: 4, shapes: [
    { shape: TETROMINO_J, required: 2, placed: 0 },
    { shape: TETROMINO_I, required: 2, placed: 0 },
    { shape: TETROMINO_O, required: 1, placed: 0 },
  ]},
  // Group 39: S + L + T (3 shapes)
  { rows: 5, cols: 5, blockCount: 4, shapes: [
    { shape: TETROMINO_S, required: 2, placed: 0 },
    { shape: TETROMINO_L, required: 2, placed: 0 },
    { shape: TETROMINO_T, required: 1, placed: 0 },
  ]},
  // Group 40: Triomino heavy (2 shapes)
  { rows: 5, cols: 5, blockCount: 4, shapes: [
    { shape: TRIOMINO_L, required: 5, placed: 0 },
    { shape: TRIOMINO_I, required: 2, placed: 0 },
  ]},
  // Group 41: J + T + O (3 shapes)
  { rows: 6, cols: 4, blockCount: 4, shapes: [
    { shape: TETROMINO_J, required: 2, placed: 0 },
    { shape: TETROMINO_T, required: 2, placed: 0 },
    { shape: TETROMINO_O, required: 1, placed: 0 },
  ]},
  // Group 42: Z + L + T (3 shapes)
  { rows: 5, cols: 5, blockCount: 4, shapes: [
    { shape: TETROMINO_Z, required: 2, placed: 0 },
    { shape: TETROMINO_L, required: 2, placed: 0 },
    { shape: TETROMINO_T, required: 1, placed: 0 },
  ]},
  // Group 43: S + J + O (3 shapes)
  { rows: 6, cols: 5, blockCount: 6, shapes: [
    { shape: TETROMINO_S, required: 2, placed: 0 },
    { shape: TETROMINO_J, required: 2, placed: 0 },
    { shape: TETROMINO_O, required: 2, placed: 0 },
  ]},
  // Group 44: 4 shapes - T,O,S,Z
  { rows: 6, cols: 4, blockCount: 4, shapes: [
    { shape: TETROMINO_T, required: 2, placed: 0 },
    { shape: TETROMINO_O, required: 1, placed: 0 },
    { shape: TETROMINO_S, required: 1, placed: 0 },
    { shape: TETROMINO_Z, required: 1, placed: 0 },
  ]},
  // Group 45: I + J (2 shapes)
  { rows: 5, cols: 4, blockCount: 4, shapes: [
    { shape: TETROMINO_I, required: 2, placed: 0 },
    { shape: TETROMINO_J, required: 2, placed: 0 },
  ]},
  // Group 46: Z + J + O (3 shapes)
  { rows: 5, cols: 5, blockCount: 4, shapes: [
    { shape: TETROMINO_Z, required: 2, placed: 0 },
    { shape: TETROMINO_J, required: 2, placed: 0 },
    { shape: TETROMINO_O, required: 1, placed: 0 },
  ]},
  // Group 47: L + S + T (3 shapes)
  { rows: 6, cols: 4, blockCount: 4, shapes: [
    { shape: TETROMINO_L, required: 2, placed: 0 },
    { shape: TETROMINO_S, required: 2, placed: 0 },
    { shape: TETROMINO_T, required: 1, placed: 0 },
  ]},
  // Group 48: J + Z (2 shapes)
  { rows: 5, cols: 4, blockCount: 4, shapes: [
    { shape: TETROMINO_J, required: 2, placed: 0 },
    { shape: TETROMINO_Z, required: 2, placed: 0 },
  ]},
  // Group 49: 5 shapes advanced
  { rows: 6, cols: 5, blockCount: 6, shapes: [
    { shape: TETROMINO_J, required: 1, placed: 0 },
    { shape: TETROMINO_L, required: 1, placed: 0 },
    { shape: TETROMINO_Z, required: 1, placed: 0 },
    { shape: TETROMINO_S, required: 1, placed: 0 },
    { shape: TETROMINO_T, required: 2, placed: 0 },
  ]},
];

const LEVEL_NAMES = [
  'Obstacle Run', 'Block Maze', 'Gap Jump', 'Narrow Path',
  'Blocked Way', 'Puzzle Pit', 'Tricky Tiles', 'Maze Runner',
  'Gap Master', 'Block Dodge', 'Tight Fit', 'Corner Case',
  'Path Finder', 'Blocked Out', 'Squeeze Play', 'Maze Craze',
  'Obstacle Course', 'Block Party', 'Gap Fill', 'Narrow Escape',
];

// Generate levels 51-200 using verified blocked cell positions
const generateLevel = (id: number): Level => {
  const difficulty = id <= 100 ? 3 : id <= 150 ? 4 : 5;
  const patternIndex = (id - 51) % GENERATED_PATTERNS.length;
  const pattern = GENERATED_PATTERNS[patternIndex];

  return {
    id,
    name: LEVEL_NAMES[(id - 51) % LEVEL_NAMES.length],
    gridRows: pattern.rows,
    gridCols: pattern.cols,
    activeCells: rect(pattern.rows, pattern.cols),
    lockedCells: [],
    blockedCells: VERIFIED_BLOCKED[id],
    requiredShapes: pattern.shapes.map(s => ({ ...s })),
    difficulty,
  };
};

// Validate a level - ensures total shape cells = paintable grid cells
const validateLevel = (level: Level): boolean => {
  const blockedCount = level.blockedCells?.length ?? 0;
  const paintableCells = level.activeCells.length - blockedCount;
  const shapeCells = level.requiredShapes.reduce((sum, item) => {
    return sum + (item.shape.pattern.length * item.required);
  }, 0);

  if (paintableCells !== shapeCells) {
    console.warn(`Level ${level.id} invalid: grid has ${paintableCells} paintable cells but shapes need ${shapeCells}`);
    return false;
  }
  return true;
};

// Create all 200 levels
export const ALL_LEVELS: Level[] = [
  LEVEL_1, LEVEL_2, LEVEL_3, LEVEL_4, LEVEL_5,
  LEVEL_6, LEVEL_7, LEVEL_8, LEVEL_9, LEVEL_10,
  LEVEL_11, LEVEL_12, LEVEL_13, LEVEL_14, LEVEL_15,
  LEVEL_16, LEVEL_17, LEVEL_18, LEVEL_19, LEVEL_20,
  LEVEL_21, LEVEL_22, LEVEL_23, LEVEL_24, LEVEL_25,
  LEVEL_26, LEVEL_27, LEVEL_28, LEVEL_29, LEVEL_30,
  LEVEL_31, LEVEL_32, LEVEL_33, LEVEL_34, LEVEL_35,
  LEVEL_36, LEVEL_37, LEVEL_38, LEVEL_39, LEVEL_40,
  LEVEL_41, LEVEL_42, LEVEL_43, LEVEL_44, LEVEL_45,
  LEVEL_46, LEVEL_47, LEVEL_48, LEVEL_49, LEVEL_50,
  ...Array.from({ length: 150 }, (_, i) => generateLevel(51 + i)),
];

// Validate all levels in development
if (typeof __DEV__ !== 'undefined' && __DEV__) {
  let allValid = true;
  ALL_LEVELS.forEach(level => {
    if (!validateLevel(level)) {
      allValid = false;
    }
  });
  if (allValid) {
    console.log('All 200 levels validated successfully');
  }
}
